# FizzBuzz 

In [1]:
def FizzBuzz():
    for x in range(1,100):
        if x % 3 == 0 and x % 5 == 0:
            print(x,'FizzBuzz')
        else:
            if x % 5 == 0:
                print(x,'Buzz')
            elif x % 3 ==0:
                print(x,'Fizz')
            else:
                print(x)

In [2]:
FizzBuzz()

1
2
3 Fizz
4
5 Buzz
6 Fizz
7
8
9 Fizz
10 Buzz
11
12 Fizz
13
14
15 FizzBuzz
16
17
18 Fizz
19
20 Buzz
21 Fizz
22
23
24 Fizz
25 Buzz
26
27 Fizz
28
29
30 FizzBuzz
31
32
33 Fizz
34
35 Buzz
36 Fizz
37
38
39 Fizz
40 Buzz
41
42 Fizz
43
44
45 FizzBuzz
46
47
48 Fizz
49
50 Buzz
51 Fizz
52
53
54 Fizz
55 Buzz
56
57 Fizz
58
59
60 FizzBuzz
61
62
63 Fizz
64
65 Buzz
66 Fizz
67
68
69 Fizz
70 Buzz
71
72 Fizz
73
74
75 FizzBuzz
76
77
78 Fizz
79
80 Buzz
81 Fizz
82
83
84 Fizz
85 Buzz
86
87 Fizz
88
89
90 FizzBuzz
91
92
93 Fizz
94
95 Buzz
96 Fizz
97
98
99 Fizz


# Fibonacci sequence  

In [3]:
n = int(input('Number of elements in Fibonacci sequence: '))
Fib_seq = []
if n == 0:
    print(Fib_seq.append(n))
else:
    a, b = 0, 1
    Fib_seq.append(a)
    Fib_seq.append(b)
    for x in range (n-1):
        a,b = b, a+b
        Fib_seq.append(b)
print(Fib_seq)

Number of elements in Fibonacci sequence: 5
[0, 1, 1, 2, 3, 5]


# Polindrom

In [4]:
word = input('Give me word: ').strip().lower()
if word == word[::-1]:
    print('Polindrom')
else: print('Not polindrom')

Give me word: fghfgh
Not polindrom


# isPrime

In [6]:
val = int(input('Give me number: '))
for i in range (2,(val-1)):
    if val % i == 0:
        print('is not Prime')
        break
else:
    print('is Prime')

Give me number: 56
is not Prime


# isPrime numbers within range

In [7]:
raw_input = input('two numbers separatred by a comma: ')
first, last = [int(x) for x in raw_input.split(',')]

def is_prime(var):
    if var == 1 or var == 0:
        return False
    else:
        for i in range (2, (var-1)):
            if var % i == 0:
                return False
                break
        else:
            return True

is_prime_list = []
for i in range(first,last):
    if is_prime(i) == True:
        is_prime_list.append(i)

print(is_prime_list)

two numbers separatred by a comma: 1,56
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53]


# BabylonSQRT
https://pl.wikipedia.org/wiki/Metody_obliczania_pierwiastka_kwadratowego#Metoda_babilo%C5%84ska

In [8]:
var = float(input('Give me a number: ').replace(',','.'))

def babylon_sqrt(var):
    
    if var >= 1:
        D = sum([1 for x in str(var).split('.')[0]])
    else:
        D = -sum([1 for x in ('%f' % var).split('.')[1] if x == '0'])
    
    if D % 2 == 0:
        x = 6*(10**((D-2)/2))
    else:
        x = 2*(10**((D-1)/2))
        

    x_i = (1/2)*(x+(var/x))


    while x != x_i:
        x = x_i
        x_i = (1/2)*(x+(var/x))
    
    return x

print(babylon_sqrt(var))

Give me a number56
7.483314773547883


# Bubble sort
https://en.wikipedia.org/wiki/Bubble_sort

In [10]:
import numpy as np
raw_input = input('Numbers separated by a comma: ')
data = np.array([int(x) for x in raw_input.split(',')])

for i in range(len(data)):
    for n in range(i+1,len(data)):
        if data[i] >data[n]:
            data[i], data[n] = data[n], data[i]
            
print(data)

Numbers separated by a comma: 45,5,5,456,456,456,45,6,45,78,4,252,85,4524,852,48
[   4    5    5    6   45   45   45   48   78   85  252  456  456  456
  852 4524]


# GROT
https://gist.github.com/sargo/8c75ba58790b230fcf08

In [11]:
sample_1 = [
    ['u', 'd', 'u', 'u'], # ↑ ↓ ↑ ↑
    ['u', 'r', 'l', 'l'], # ↑ → ← ←
    ['u', 'u', 'l', 'u'], # ↑ ↑ ← ↑
    ['l', 'd', 'u', 'l'], # ← ↓ ↑ ←
]
sample_2 = [
    ['u', 'd', 'u', 'u', 'u', 'd', 'u', 'u'],
    ['u', 'u', 'l', 'u', 'u', 'u', 'l', 'u'],
    ['u', 'l', 'l', 'l', 'u', 'r', 'l', 'l'],
    ['l', 'd', 'u', 'l', 'l', 'd', 'u', 'l'],
    ['d', 'u', 'l', 'd', 'u', 'l', 'd', 'u'],
]


class path(object):
    
    def __init__(self,x,y,sample):
        
        self.path = [(x,y)]
        self.x = x
        self.y = y
        self.sample = sample
        
    def run(self):
           
        while (self.x,self.y) not in self.path[:-1] and self.x >= 0 and self.x < len(self.sample) and self.y >= 0 and self.y < len(self.sample[0]):
                    
            if self.sample[self.x][self.y] == 'u':
                self.x -= 1
                self.path.append((self.x,self.y))
            
            elif self.sample[self.x][self.y] == 'd':
                self.x += 1
                self.path.append((self.x,self.y))
                
            elif self.sample[self.x][self.y] == 'r':
                self.y += 1
                self.path.append((self.x,self.y))
                
            elif self.sample[self.x][self.y] == 'l':
                self.y -= 1
                self.path.append((self.x,self.y))
                
    def get_path(self):
        return self.path
        
def find_way(sample):
    
    all_way = []
    
    for y in range(len(sample)):
        for x in range(len(sample[0])):
            sample_path = path(x,y,sample)
            sample_path.run()
            all_way.append(sample_path.get_path())
    
    idx,length = sorted(enumerate([len(x) for x in all_way]), key = lambda x: x[1])[-1]
    
    return all_way[idx]
    
    
print(find_way(sample_2))
print(find_way(sample_1))

[(4, 4), (3, 4), (3, 3), (3, 2), (2, 2), (2, 1), (2, 0), (1, 0), (0, 0), (-1, 0)]
[(3, 3), (3, 2), (2, 2), (2, 1), (1, 1), (1, 2), (1, 1)]


# WeirdText
https://gist.github.com/sargo/e3a4d72fbdace178e1b6

In [26]:
text = 'This is a long looooong test sentence, \n with some big (biiiiig) words!'

def shuffle_words_decorator(func):
    def wraper(text):
        print('\n---weird---\n')
        shuffled_text = func(text)
        print('\n---weird---\n')
        shuffled_text = '\n---weird---\n' + shuffled_text + '\n---weird---\n'
        return shuffled_text 
    return wraper

@shuffle_words_decorator
def shuffle_words(text):
    
    import random
    import string

    shuffled_text=[]
    for x in text.split(' '):
        if len(x) > 3:
            for y in range(len(x)):
                if x[y] in string.ascii_lowercase or x[y] in string.ascii_uppercase:
                    first_idx = y
                    break

            for y in range(1,len(x)):
                y=-y
                if x[y] in string.ascii_lowercase or x[y] in string.ascii_uppercase:
                    last_idx = y
                    break

            sliced = x[first_idx+1:last_idx]
            sliced_shuffled_raw = list(sliced)
            random.shuffle(sliced_shuffled_raw)
            sliced_shuffled = ''.join(sliced_shuffled_raw)

            if len(set(list(sliced))) != 1: #remove problem with all letters inside word are the same (biiiiiiiig)
                while sliced == sliced_shuffled: #remove problem with lack of shuffle in small words like 'This'
                    sliced_shuffled_raw = list(sliced)
                    random.shuffle(sliced_shuffled_raw)
                    sliced_shuffled = ''.join(sliced_shuffled_raw)

            shuffled_word = x[:first_idx+1]+sliced_shuffled+x[last_idx:]
            shuffled_text.append(shuffled_word)

        else: shuffled_text.append(x) 
            
    shuffled_text = ' '.join(shuffled_text)
    print(shuffled_text)
    return shuffled_text
    
    
def shuffle_text(text):
    
    import random
    
    shuffled_text = text.split(' ')
    random.shuffle(shuffled_text)
    shuffled_text = ' '.join(shuffled_text)
    
    print(shuffled_text)
    
    return shuffled_text
     
    
def encoder(text):
    words_shuffled = shuffle_words(text)
    text_shuffled = shuffle_text(text)
    encoded_text = str(words_shuffled) + str(text_shuffled)
     
    return encoded_text

def decoder(text):
    text_to_decode = text.split('\n---weird---\n')[1:]
    decoded_text = []
    for word_shuffled in text_to_decode[0].split(' '):
        for word_clear in text_to_decode[1].split(' '):
            if sorted(list(word_shuffled)) == sorted(list(word_clear)):
                decoded_text.append(word_clear)
    decoded_text = ' '.join(decoded_text)
    print (decoded_text)
    return decoded_text


In [27]:
text_encoded = encoder(text)


---weird---

Tihs is a lnog lonoooog tset sntcneee, 
 wtih smoe big (biiiiig) wrods!

---weird---

(biiiiig) test with a words! long looooong sentence, some This big 
 is


In [28]:
text_decoded = decoder(text_encoded)

This is a long looooong test sentence, 
 with some big (biiiiig) words!


In [29]:
print(text)

This is a long looooong test sentence, 
 with some big (biiiiig) words!


In [30]:
text_decoded == text

True

# Unwrapping A Spiral
https://programmingpraxis.com/2010/06/01/unwrapping-a-spiral/

In [1]:
import numpy as np
mtx = np.random.randint(0,10,size =(5,5))

def spiral_wrapper(mtx):
    spiral = []
    while mtx.shape[0] != 0:
        
        [spiral.append(x) for x in mtx[0]]
        mtx = np.delete(mtx,0,axis=0)
        mtx = np.rot90(mtx)
        
    return spiral

In [2]:
for x,y in [(5,5),(10,5),(5,10)]:
    mtx = np.random.randint(0,10, size =(x,y))
    print("\nmatrix\n",mtx)
    print("\nspiral wrapping", spiral_wrapper(mtx))


matrix
 [[2 4 5 4 4]
 [9 5 2 5 4]
 [4 4 3 3 9]
 [8 8 1 9 6]
 [8 5 9 7 3]]

spiral wrapping [2, 4, 5, 4, 4, 4, 9, 6, 3, 7, 9, 5, 8, 8, 4, 9, 5, 2, 5, 3, 9, 1, 8, 4, 3]

matrix
 [[7 1 5 9 7]
 [0 0 2 8 6]
 [3 8 1 1 2]
 [0 4 8 7 7]
 [2 2 9 4 0]
 [3 5 6 2 4]
 [2 2 6 7 9]
 [3 9 1 8 4]
 [8 9 8 8 9]
 [6 7 9 0 8]]

spiral wrapping [7, 1, 5, 9, 7, 6, 2, 7, 0, 4, 9, 4, 9, 8, 0, 9, 7, 6, 8, 3, 2, 3, 2, 0, 3, 0, 0, 2, 8, 1, 7, 4, 2, 7, 8, 8, 8, 9, 9, 2, 5, 2, 4, 8, 1, 8, 9, 6, 6, 1]

matrix
 [[3 8 8 1 3 2 8 3 4 2]
 [5 3 5 7 6 6 4 3 3 4]
 [2 6 7 6 0 2 5 0 7 7]
 [8 9 0 3 9 8 3 6 8 1]
 [6 2 9 4 0 5 1 9 3 3]]

spiral wrapping [3, 8, 8, 1, 3, 2, 8, 3, 4, 2, 4, 7, 1, 3, 3, 9, 1, 5, 0, 4, 9, 2, 6, 8, 2, 5, 3, 5, 7, 6, 6, 4, 3, 3, 7, 8, 6, 3, 8, 9, 3, 0, 9, 6, 7, 6, 0, 2, 5, 0]
